name       : PyAudio
version    : 0.2.11
release    : 5
source     :
    - https://pypi.python.org/packages/ab/42/b4f04721c5c5bfc196ce156b3c768998ef8c0ae3654ed29ea5020c749a6b/PyAudio-0.2.11.tar.gz : 93bfde30e0b64e63a46f2fd77e85c41fd51182a4a3413d9edfaf9ffaa26efb74
license    : MIT
component  : programming.python
summary    : PyAudio provides Python bindings for PortAudio, the cross-platform audio I/O library.
description: |
    PyAudio provides Python bindings for PortAudio, the cross-platform audio I/O library.
builddeps  :
    - pkgconfig(portaudiocpp)
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
