name       : PyAudio
version    : 0.2.12
release    : 6
source     :
    - https://pypi.python.org/packages/source/P/PyAudio/PyAudio-0.2.12.tar.gz : 55ddf5db72bc537bba5f5dbca3ab9f0222ee5b842bda83978eab0b7b8f60fb9e
homepage   : https://people.csail.mit.edu/hubert/pyaudio/
license    : MIT
component  : programming.python
summary    : Cross-platform audio I/O with PortAudio
description: |
    PyAudio provides Python bindings for PortAudio, the cross-platform audio I/O library.
builddeps  :
    - pkgconfig(portaudiocpp)
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
